import type { HolidayCountry } from "$lib/shared/types";

export const countries: HolidayCountry[][] = [
  [
    { code: "US", name: "United States" },
    { code: "IN", name: "India" },
    { code: "CN", name: "China" },
    { code: "JP", name: "Japan" },
    { code: "DE", name: "Germany" },
    { code: "GB", name: "United Kingdom" },
    { code: "KR", name: "Korea, Republic of" },
    { code: "BR", name: "Brazil" },
    { code: "ID", name: "Indonesia" },
    { code: "FR", name: "France" },
    { code: "CA", name: "Canada" },
    { code: "AU", name: "Australia" },
    { code: "ES", name: "Spain" },
    { code: "IT", name: "Italy" },
    { code: "MX", name: "Mexico" },
    { code: "NL", name: "Netherlands" },
    { code: "SG", name: "Singapore" },
    { code: "SE", name: "Sweden" },
    { code: "CH", name: "Switzerland" },
    { code: "AE", name: "United Arab Emirates" },
    { code: "PL", name: "Poland" },
    { code: "TH", name: "Thailand" },
    { code: "SA", name: "Saudi Arabia" },
    { code: "TR", name: "Turkey" },
    { code: "PH", name: "Philippines" },
    { code: "VN", name: "Viet Nam" },
    { code: "CZ", name: "Czechia" },
    { code: "CL", name: "Chile" },
    { code: "AR", name: "Argentina" },
    { code: "MY", name: "Malaysia" },
    { code: "BE", name: "Belgium" },
    { code: "AT", name: "Austria" },
    { code: "NO", name: "Norway" },
    { code: "DK", name: "Denmark" },
    { code: "MM", name: "Myanmar" },
    { code: "IE", name: "Ireland" },
    { code: "FI", name: "Finland" },
    { code: "TW", name: "Taiwan, Province of China" },
    { code: "GR", name: "Greece" },
    { code: "PT", name: "Portugal" }
  ],
  // Batch 2: Next tier based on internet usage, smartphone penetration, and growing digital economies
  [
    { code: "RU", name: "Russian Federation" },
    { code: "ZA", name: "South Africa" },
    { code: "EG", name: "Egypt" },
    { code: "PK", name: "Pakistan" },
    { code: "CO", name: "Colombia" },
    { code: "PE", name: "Peru" },
    { code: "CR", name: "Costa Rica" },
    { code: "DO", name: "Dominican Republic" },
    { code: "HU", name: "Hungary" },
    { code: "NZ", name: "New Zealand" },
    { code: "UA", name: "Ukraine" },
    { code: "AZ", name: "Azerbaijan" },
    { code: "BY", name: "Belarus" },
    { code: "BG", name: "Bulgaria" },
    { code: "HR", name: "Croatia" },
    { code: "EE", name: "Estonia" },
    { code: "GE", name: "Georgia" },
    { code: "LV", name: "Latvia" },
    { code: "LT", name: "Lithuania" },
    { code: "LU", name: "Luxembourg" },
    { code: "MT", name: "Malta" },
    { code: "OM", name: "Oman" },
    { code: "QA", name: "Qatar" },
    { code: "RO", name: "Romania" },
    { code: "RS", name: "Serbia" },
    { code: "SK", name: "Slovakia" },
    { code: "SI", name: "Slovenia" },
    { code: "UY", name: "Uruguay" },
    { code: "UZ", name: "Uzbekistan" },
    { code: "VN", name: "Viet Nam" },
    { code: "AL", name: "Albania" },
    { code: "AD", name: "Andorra" },
    { code: "AM", name: "Armenia" },
    { code: "BH", name: "Bahrain" },
    { code: "BA", name: "Bosnia and Herzegovina" },
    { code: "CY", name: "Cyprus" },
    { code: "IS", name: "Iceland" },
    { code: "KW", name: "Kuwait" },
    { code: "MD", name: "Moldova, Republic of" },
    { code: "ME", name: "Montenegro" }
  ],
  // Batch 3: Remaining with reasonable internet access or notable potential
  [
    { code: "AR", name: "Argentina" },
    { code: "AW", name: "Aruba" },
    { code: "BD", name: "Bangladesh" },
    { code: "BY", name: "Belarus" },
    { code: "BZ", name: "Belize" },
    { code: "BT", name: "Bhutan" },
    { code: "BO", name: "Bolivia" },
    { code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
    { code: "BF", name: "Burkina Faso" },
    { code: "KH", name: "Cambodia" },
    { code: "CM", name: "Cameroon" },
    { code: "CV", name: "Cabo Verde" },
    { code: "KY", name: "Cayman Islands" },
    { code: "CI", name: "Côte d'Ivoire" },
    { code: "CU", name: "Cuba" },
    { code: "CW", name: "Curaçao" },
    { code: "DJ", name: "Djibouti" },
    { code: "EC", name: "Ecuador" },
    { code: "GQ", name: "Equatorial Guinea" },
    { code: "ER", name: "Eritrea" },
    { code: "ET", name: "Ethiopia" },
    { code: "FO", name: "Faroe Islands" },
    { code: "GM", name: "Gambia" },
    { code: "GH", name: "Ghana" },
    { code: "GL", name: "Greenland" },
    { code: "GD", name: "Grenada" },
    { code: "GP", name: "Guadeloupe" },
    { code: "GU", name: "Guam" },
    { code: "GT", name: "Guatemala" },
    { code: "GG", name: "Guernsey" },
    { code: "GN", name: "Guinea" },
    { code: "GW", name: "Guinea-Bissau" },
    { code: "GY", name: "Guyana" },
    { code: "HT", name: "Haiti" },
    { code: "HM", name: "Heard Island and McDonald Islands" },
    { code: "VA", name: "Holy See" },
    { code: "HN", name: "Honduras" },
    { code: "HK", name: "Hong Kong" },
    { code: "IM", name: "Isle of Man" }
  ],
  // Batch 4: Remaining countries
  [
    { code: "JM", name: "Jamaica" },
    { code: "JE", name: "Jersey" },
    { code: "JO", name: "Jordan" },
    { code: "KE", name: "Kenya" },
    { code: "KI", name: "Kiribati" },
    { code: "KG", name: "Kyrgyzstan" },
    { code: "LA", name: "Lao People's Democratic Republic" },
    { code: "LB", name: "Lebanon" },
    { code: "LS", name: "Lesotho" },
    { code: "LR", name: "Liberia" },
    { code: "LY", name: "Libya" },
    { code: "MO", name: "Macao" },
    { code: "MG", name: "Madagascar" },
    { code: "MW", name: "Malawi" },
    { code: "MV", name: "Maldives" },
    { code: "ML", name: "Mali" },
    { code: "MH", name: "Marshall Islands" },
    { code: "MQ", name: "Martinique" },
    { code: "MR", name: "Mauritania" },
    { code: "MU", name: "Mauritius" },
    { code: "YT", name: "Mayotte" },
    { code: "FM", name: "Micronesia, Federated States of" },
    { code: "MN", name: "Mongolia" },
    { code: "MS", name: "Montserrat" },
    { code: "MA", name: "Morocco" },
    { code: "MZ", name: "Mozambique" },
    { code: "IL", name: "Israel" },
    { code: "NA", name: "Namibia" },
    { code: "NR", name: "Nauru" },
    { code: "NP", name: "Nepal" },
    { code: "NC", name: "New Caledonia" },
    { code: "NI", name: "Nicaragua" },
    { code: "NE", name: "Niger" },
    { code: "NU", name: "Niue" },
    { code: "NF", name: "Norfolk Island" },
    { code: "MK", name: "North Macedonia" },
    { code: "MP", name: "Northern Mariana Islands" },
    { code: "PA", name: "Panama" },
    { code: "PG", name: "Papua New Guinea" }
  ],
  // Batch 5: Remaining countries (fewer tech users, but still include for completeness)
  [
    { code: "PS", name: "Palestine, State of" },
    { code: "PY", name: "Paraguay" },
    { code: "PH", name: "Philippines" },
    { code: "PN", name: "Pitcairn" },
    { code: "PR", name: "Puerto Rico" },
    { code: "RE", name: "Réunion" },
    { code: "RW", name: "Rwanda" },
    { code: "BL", name: "Saint Barthélemy" },
    { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" },
    { code: "KN", name: "Saint Kitts and Nevis" },
    { code: "LC", name: "Saint Lucia" },
    { code: "MF", name: "Saint Martin (French part)" },
    { code: "PM", name: "Saint Pierre and Miquelon" },
    { code: "VC", name: "Saint Vincent and the Grenadines" },
    { code: "WS", name: "Samoa" },
    { code: "SM", name: "San Marino" },
    { code: "ST", name: "Sao Tome and Principe" },
    { code: "SC", name: "Seychelles" },
    { code: "SL", name: "Sierra Leone" },
    { code: "SO", name: "Somalia" },
    { code: "GS", name: "South Georgia and the South Sandwich Islands" },
    { code: "SS", name: "South Sudan" },
    { code: "LK", name: "Sri Lanka" },
    { code: "SD", name: "Sudan" },
    { code: "SR", name: "Suriname" },
    { code: "SJ", name: "Svalbard and Jan Mayen" },
    { code: "SY", name: "Syrian Arab Republic" },
    { code: "TJ", name: "Tajikistan" },
    { code: "TZ", name: "Tanzania, United Republic of" },
    { code: "TL", name: "Timor-Leste" },
    { code: "TG", name: "Togo" },
    { code: "TK", name: "Tokelau" },
    { code: "TO", name: "Tonga" },
    { code: "TT", name: "Trinidad and Tobago" },
    { code: "TN", name: "Tunisia" },
    { code: "TM", name: "Turkmenistan" },
    { code: "TC", name: "Turks and Caicos Islands" },
    { code: "TV", name: "Tuvalu" },
    { code: "UM", name: "United States Minor Outlying Islands" },
    { code: "VE", name: "Venezuela, Bolivarian Republic of" },
    { code: "VG", name: "Virgin Islands, British" },
    { code: "VI", name: "Virgin Islands, U.S." },
    { code: "VU", name: "Vanuatu" },
    { code: "WF", name: "Wallis and Futuna" },
    { code: "EH", name: "Western Sahara" },
    { code: "YE", name: "Yemen" },
    { code: "ZM", name: "Zambia" },
    { code: "ZW", name: "Zimbabwe" },
    { code: "AX", name: "Åland Islands" }
  ]
];
