import type { HolidayCountry } from "$lib/shared/types";

export const countries: HolidayCountry[][] = [
  [
    { id: "us", colorId: "21", countryCode: "US", countryName: "United States" },
    { id: "in", colorId: "1", countryCode: "IN", countryName: "India" },
    { id: "cn", colorId: "24", countryCode: "CN", countryName: "China" },
    { id: "jp", colorId: "13", countryCode: "JP", countryName: "Japan" },
    { id: "de", colorId: "9", countryCode: "DE", countryName: "Germany" },
    { id: "gb", colorId: "11", countryCode: "GB", countryName: "United Kingdom" },
    { id: "kr", colorId: "12", countryCode: "KR", countryName: "Korea, Republic of" },
    { id: "br", colorId: "10", countryCode: "BR", countryName: "Brazil" },
    { id: "id", colorId: "1", countryCode: "ID", countryName: "Indonesia" },
    { id: "fr", colorId: "3", countryCode: "FR", countryName: "France" },
    { id: "ca", colorId: "22", countryCode: "CA", countryName: "Canada" },
    { id: "au", colorId: "14", countryCode: "AU", countryName: "Australia" },
    { id: "es", colorId: "15", countryCode: "ES", countryName: "Spain" },
    { id: "it", colorId: "23", countryCode: "IT", countryName: "Italy" },
    { id: "mx", colorId: "5", countryCode: "MX", countryName: "Mexico" },
    { id: "nl", colorId: "16", countryCode: "NL", countryName: "Netherlands" },
    { id: "sg", colorId: "1", countryCode: "SG", countryName: "Singapore" },
    { id: "se", colorId: "17", countryCode: "SE", countryName: "Sweden" },
    { id: "ch", colorId: "24", countryCode: "CH", countryName: "Switzerland" },
    { id: "ae", colorId: "20", countryCode: "AE", countryName: "United Arab Emirates" },
    { id: "pl", colorId: "18", countryCode: "PL", countryName: "Poland" },
    { id: "th", colorId: "19", countryCode: "TH", countryName: "Thailand" },
    { id: "sa", colorId: "2", countryCode: "SA", countryName: "Saudi Arabia" },
    { id: "tr", colorId: "4", countryCode: "TR", countryName: "Turkey" },
    { id: "ph", colorId: "1", countryCode: "PH", countryName: "Philippines" },
    { id: "vn", colorId: "6", countryCode: "VN", countryName: "Vietnam" },
    { id: "cz", colorId: "7", countryCode: "CZ", countryName: "Czechia" },
    { id: "cl", colorId: "8", countryCode: "CL", countryName: "Chile" },
    { id: "ar", colorId: "9", countryCode: "AR", countryName: "Argentina" },
    { id: "my", colorId: "10", countryCode: "MY", countryName: "Malaysia" },
    { id: "be", colorId: "11", countryCode: "BE", countryName: "Belgium" },
    { id: "at", colorId: "12", countryCode: "AT", countryName: "Austria" },
    { id: "no", colorId: "13", countryCode: "NO", countryName: "Norway" },
    { id: "dk", colorId: "14", countryCode: "DK", countryName: "Denmark" },
    { id: "mm", colorId: "15", countryCode: "MM", countryName: "Myanmar" },
    { id: "ie", colorId: "16", countryCode: "IE", countryName: "Ireland" },
    { id: "fi", colorId: "17", countryCode: "FI", countryName: "Finland" },
    { id: "tw", colorId: "18", countryCode: "TW", countryName: "Taiwan, Province of China" },
    { id: "gr", colorId: "19", countryCode: "GR", countryName: "Greece" },
    { id: "pt", colorId: "20", countryCode: "PT", countryName: "Portugal" }
  ],
  // Batch 2: Next tier based on internet usage, smartphone penetration, and growing digital economies
  [
    { id: "ru", colorId: "21", countryCode: "RU", countryName: "Russian Federation" },
    { id: "za", colorId: "22", countryCode: "ZA", countryName: "South Africa" },
    { id: "eg", colorId: "23", countryCode: "EG", countryName: "Egypt" },
    { id: "pk", colorId: "24", countryCode: "PK", countryName: "Pakistan" },
    { id: "co", colorId: "1", countryCode: "CO", countryName: "Colombia" },
    { id: "pe", colorId: "2", countryCode: "PE", countryName: "Peru" },
    { id: "cr", colorId: "3", countryCode: "CR", countryName: "Costa Rica" },
    { id: "do", colorId: "4", countryCode: "DO", countryName: "Dominican Republic" },
    { id: "hu", colorId: "5", countryCode: "HU", countryName: "Hungary" },
    { id: "nz", colorId: "6", countryCode: "NZ", countryName: "New Zealand" },
    { id: "ua", colorId: "7", countryCode: "UA", countryName: "Ukraine" },
    { id: "az", colorId: "8", countryCode: "AZ", countryName: "Azerbaijan" },
    { id: "by", colorId: "9", countryCode: "BY", countryName: "Belarus" },
    { id: "bg", colorId: "10", countryCode: "BG", countryName: "Bulgaria" },
    { id: "hr", colorId: "11", countryCode: "HR", countryName: "Croatia" },
    { id: "ee", colorId: "12", countryCode: "EE", countryName: "Estonia" },
    { id: "ge", colorId: "13", countryCode: "GE", countryName: "Georgia" },
    { id: "lv", colorId: "14", countryCode: "LV", countryName: "Latvia" },
    { id: "lt", colorId: "15", countryCode: "LT", countryName: "Lithuania" },
    { id: "lu", colorId: "16", countryCode: "LU", countryName: "Luxembourg" },
    { id: "mt", colorId: "17", countryCode: "MT", countryName: "Malta" },
    { id: "om", colorId: "18", countryCode: "OM", countryName: "Oman" },
    { id: "qa", colorId: "19", countryCode: "QA", countryName: "Qatar" },
    { id: "ro", colorId: "20", countryCode: "RO", countryName: "Romania" },
    { id: "rs", colorId: "21", countryCode: "RS", countryName: "Serbia" },
    { id: "sk", colorId: "22", countryCode: "SK", countryName: "Slovakia" },
    { id: "si", colorId: "23", countryCode: "SI", countryName: "Slovenia" },
    { id: "uy", colorId: "24", countryCode: "UY", countryName: "Uruguay" },
    { id: "uz", colorId: "1", countryCode: "UZ", countryName: "Uzbekistan" },
    { id: "vn", colorId: "2", countryCode: "VN", countryName: "Vietnam" },
    { id: "al", colorId: "3", countryCode: "AL", countryName: "Albania" },
    { id: "ad", colorId: "4", countryCode: "AD", countryName: "Andorra" },
    { id: "am", colorId: "5", countryCode: "AM", countryName: "Armenia" },
    { id: "bh", colorId: "6", countryCode: "BH", countryName: "Bahrain" },
    { id: "ba", colorId: "7", countryCode: "BA", countryName: "Bosnia and Herzegovina" },
    { id: "cy", colorId: "8", countryCode: "CY", countryName: "Cyprus" },
    { id: "is", colorId: "9", countryCode: "IS", countryName: "Iceland" },
    { id: "kw", colorId: "10", countryCode: "KW", countryName: "Kuwait" },
    { id: "md", colorId: "11", countryCode: "MD", countryName: "Moldova, Republic of" },
    { id: "me", colorId: "12", countryCode: "ME", countryName: "Montenegro" }
  ],
  // Batch 3: Remaining with reasonable internet access or notable potential
  [
    { id: "ar", colorId: "13", countryCode: "AR", countryName: "Argentina" },
    { id: "aw", colorId: "14", countryCode: "AW", countryName: "Aruba" },
    { id: "bd", colorId: "15", countryCode: "BD", countryName: "Bangladesh" },
    { id: "by", colorId: "16", countryCode: "BY", countryName: "Belarus" },
    { id: "bz", colorId: "17", countryCode: "BZ", countryName: "Belize" },
    { id: "bt", colorId: "18", countryCode: "BT", countryName: "Bhutan" },
    { id: "bo", colorId: "19", countryCode: "BO", countryName: "Bolivia" },
    { id: "bq", colorId: "20", countryCode: "BQ", countryName: "Bonaire, Sint Eustatius and Saba" },
    { id: "bf", colorId: "21", countryCode: "BF", countryName: "Burkina Faso" },
    { id: "kh", colorId: "22", countryCode: "KH", countryName: "Cambodia" },
    { id: "cm", colorId: "23", countryCode: "CM", countryName: "Cameroon" },
    { id: "cv", colorId: "24", countryCode: "CV", countryName: "Cabo Verde" },
    { id: "ky", colorId: "1", countryCode: "KY", countryName: "Cayman Islands" },
    { id: "ci", colorId: "2", countryCode: "CI", countryName: "Côte d'Ivoire" },
    { id: "cu", colorId: "3", countryCode: "CU", countryName: "Cuba" },
    { id: "cw", colorId: "4", countryCode: "CW", countryName: "Curaçao" },
    { id: "dj", colorId: "5", countryCode: "DJ", countryName: "Djibouti" },
    { id: "ec", colorId: "6", countryCode: "EC", countryName: "Ecuador" },
    { id: "gq", colorId: "7", countryCode: "GQ", countryName: "Equatorial Guinea" },
    { id: "er", colorId: "8", countryCode: "ER", countryName: "Eritrea" },
    { id: "et", colorId: "9", countryCode: "ET", countryName: "Ethiopia" },
    { id: "fo", colorId: "10", countryCode: "FO", countryName: "Faroe Islands" },
    { id: "gm", colorId: "11", countryCode: "GM", countryName: "Gambia" },
    { id: "gh", colorId: "12", countryCode: "GH", countryName: "Ghana" },
    { id: "gl", colorId: "13", countryCode: "GL", countryName: "Greenland" },
    { id: "gd", colorId: "14", countryCode: "GD", countryName: "Grenada" },
    { id: "gp", colorId: "15", countryCode: "GP", countryName: "Guadeloupe" },
    { id: "gu", colorId: "16", countryCode: "GU", countryName: "Guam" },
    { id: "gt", colorId: "17", countryCode: "GT", countryName: "Guatemala" },
    { id: "gg", colorId: "18", countryCode: "GG", countryName: "Guernsey" },
    { id: "gn", colorId: "19", countryCode: "GN", countryName: "Guinea" },
    { id: "gw", colorId: "20", countryCode: "GW", countryName: "Guinea-Bissau" },
    { id: "gy", colorId: "21", countryCode: "GY", countryName: "Guyana" },
    { id: "ht", colorId: "22", countryCode: "HT", countryName: "Haiti" },
    {
      id: "hm",
      colorId: "23",
      countryCode: "HM",
      countryName: "Heard Island and McDonald Islands"
    },
    { id: "va", colorId: "24", countryCode: "VA", countryName: "Holy See" },
    { id: "hn", colorId: "1", countryCode: "HN", countryName: "Honduras" },
    { id: "hk", colorId: "2", countryCode: "HK", countryName: "Hong Kong" },
    { id: "im", colorId: "3", countryCode: "IM", countryName: "Isle of Man" }
  ],
  // Batch 4: Remaining countries
  [
    { id: "jm", colorId: "4", countryCode: "JM", countryName: "Jamaica" },
    { id: "je", colorId: "5", countryCode: "JE", countryName: "Jersey" },
    { id: "jo", colorId: "6", countryCode: "JO", countryName: "Jordan" },
    { id: "ke", colorId: "7", countryCode: "KE", countryName: "Kenya" },
    { id: "ki", colorId: "8", countryCode: "KI", countryName: "Kiribati" },
    { id: "kg", colorId: "9", countryCode: "KG", countryName: "Kyrgyzstan" },
    { id: "la", colorId: "10", countryCode: "LA", countryName: "Lao People's Democratic Republic" },
    { id: "lb", colorId: "11", countryCode: "LB", countryName: "Lebanon" },
    { id: "ls", colorId: "12", countryCode: "LS", countryName: "Lesotho" },
    { id: "lr", colorId: "13", countryCode: "LR", countryName: "Liberia" },
    { id: "ly", colorId: "14", countryCode: "LY", countryName: "Libya" },
    { id: "mo", colorId: "15", countryCode: "MO", countryName: "Macao" },
    { id: "mg", colorId: "16", countryCode: "MG", countryName: "Madagascar" },
    { id: "mw", colorId: "17", countryCode: "MW", countryName: "Malawi" },
    { id: "mv", colorId: "18", countryCode: "MV", countryName: "Maldives" },
    { id: "ml", colorId: "19", countryCode: "ML", countryName: "Mali" },
    { id: "mh", colorId: "20", countryCode: "MH", countryName: "Marshall Islands" },
    { id: "mq", colorId: "21", countryCode: "MQ", countryName: "Martinique" },
    { id: "mr", colorId: "22", countryCode: "MR", countryName: "Mauritania" },
    { id: "mu", colorId: "23", countryCode: "MU", countryName: "Mauritius" },
    { id: "yt", colorId: "24", countryCode: "YT", countryName: "Mayotte" },
    { id: "fm", colorId: "1", countryCode: "FM", countryName: "Micronesia, Federated States of" },
    { id: "mn", colorId: "2", countryCode: "MN", countryName: "Mongolia" },
    { id: "ms", colorId: "3", countryCode: "MS", countryName: "Montserrat" },
    { id: "ma", colorId: "4", countryCode: "MA", countryName: "Morocco" },
    { id: "mz", colorId: "5", countryCode: "MZ", countryName: "Mozambique" },
    { id: "il", colorId: "6", countryCode: "IL", countryName: "Israel" },
    { id: "na", colorId: "7", countryCode: "NA", countryName: "Namibia" },
    { id: "nr", colorId: "8", countryCode: "NR", countryName: "Nauru" },
    { id: "np", colorId: "9", countryCode: "NP", countryName: "Nepal" },
    { id: "nc", colorId: "10", countryCode: "NC", countryName: "New Caledonia" },
    { id: "ni", colorId: "11", countryCode: "NI", countryName: "Nicaragua" },
    { id: "ne", colorId: "12", countryCode: "NE", countryName: "Niger" },
    { id: "nu", colorId: "13", countryCode: "NU", countryName: "Niue" },
    { id: "nf", colorId: "14", countryCode: "NF", countryName: "Norfolk Island" },
    { id: "mk", colorId: "15", countryCode: "MK", countryName: "North Macedonia" },
    { id: "mp", colorId: "16", countryCode: "MP", countryName: "Northern Mariana Islands" },
    { id: "pa", colorId: "17", countryCode: "PA", countryName: "Panama" },
    { id: "pg", colorId: "18", countryCode: "PG", countryName: "Papua New Guinea" }
  ],
  // Batch 5: Remaining countries (fewer tech users, but still include for completeness)
  [
    { id: "ps", colorId: "19", countryCode: "PS", countryName: "Palestine, State of" },
    { id: "py", colorId: "20", countryCode: "PY", countryName: "Paraguay" },
    { id: "ph", colorId: "21", countryCode: "PH", countryName: "Philippines" },
    { id: "pn", colorId: "22", countryCode: "PN", countryName: "Pitcairn" },
    { id: "pr", colorId: "23", countryCode: "PR", countryName: "Puerto Rico" },
    { id: "re", colorId: "24", countryCode: "RE", countryName: "Réunion" },
    { id: "rw", colorId: "1", countryCode: "RW", countryName: "Rwanda" },
    { id: "bl", colorId: "2", countryCode: "BL", countryName: "Saint Barthélemy" },
    {
      id: "sh",
      colorId: "3",
      countryCode: "SH",
      countryName: "Saint Helena, Ascension and Tristan da Cunha"
    },
    { id: "kn", colorId: "4", countryCode: "KN", countryName: "Saint Kitts and Nevis" },
    { id: "lc", colorId: "5", countryCode: "LC", countryName: "Saint Lucia" },
    { id: "mf", colorId: "6", countryCode: "MF", countryName: "Saint Martin (French part)" },
    { id: "pm", colorId: "7", countryCode: "PM", countryName: "Saint Pierre and Miquelon" },
    { id: "vc", colorId: "8", countryCode: "VC", countryName: "Saint Vincent and the Grenadines" },
    { id: "ws", colorId: "9", countryCode: "WS", countryName: "Samoa" },
    { id: "sm", colorId: "10", countryCode: "SM", countryName: "San Marino" },
    { id: "st", colorId: "11", countryCode: "ST", countryName: "Sao Tome and Principe" },
    { id: "sc", colorId: "12", countryCode: "SC", countryName: "Seychelles" },
    { id: "sl", colorId: "13", countryCode: "SL", countryName: "Sierra Leone" },
    { id: "so", colorId: "14", countryCode: "SO", countryName: "Somalia" },
    {
      id: "gs",
      colorId: "15",
      countryCode: "GS",
      countryName: "South Georgia and the South Sandwich Islands"
    },
    { id: "ss", colorId: "16", countryCode: "SS", countryName: "South Sudan" },
    { id: "lk", colorId: "17", countryCode: "LK", countryName: "Sri Lanka" },
    { id: "sd", colorId: "18", countryCode: "SD", countryName: "Sudan" },
    { id: "sr", colorId: "19", countryCode: "SR", countryName: "Suriname" },
    { id: "sj", colorId: "20", countryCode: "SJ", countryName: "Svalbard and Jan Mayen" },
    { id: "sy", colorId: "21", countryCode: "SY", countryName: "Syrian Arab Republic" },
    { id: "tj", colorId: "22", countryCode: "TJ", countryName: "Tajikistan" },
    { id: "tz", colorId: "23", countryCode: "TZ", countryName: "Tanzania, United Republic of" },
    { id: "tl", colorId: "24", countryCode: "TL", countryName: "Timor-Leste" },
    { id: "tg", colorId: "1", countryCode: "TG", countryName: "Togo" },
    { id: "tk", colorId: "2", countryCode: "TK", countryName: "Tokelau" },
    { id: "to", colorId: "3", countryCode: "TO", countryName: "Tonga" },
    { id: "tt", colorId: "4", countryCode: "TT", countryName: "Trinidad and Tobago" },
    { id: "tn", colorId: "5", countryCode: "TN", countryName: "Tunisia" },
    { id: "tm", colorId: "6", countryCode: "TM", countryName: "Turkmenistan" },
    { id: "tc", colorId: "7", countryCode: "TC", countryName: "Turks and Caicos Islands" },
    { id: "tv", colorId: "8", countryCode: "TV", countryName: "Tuvalu" },
    {
      id: "um",
      colorId: "9",
      countryCode: "UM",
      countryName: "United States Minor Outlying Islands"
    },
    {
      id: "ve",
      colorId: "10",
      countryCode: "VE",
      countryName: "Venezuela, Bolivarian Republic of"
    },
    { id: "vg", colorId: "11", countryCode: "VG", countryName: "Virgin Islands, British" },
    { id: "vi", colorId: "12", countryCode: "VI", countryName: "Virgin Islands, U.S." },
    { id: "vu", colorId: "13", countryCode: "VU", countryName: "Vanuatu" },
    { id: "wf", colorId: "14", countryCode: "WF", countryName: "Wallis and Futuna" },
    { id: "eh", colorId: "15", countryCode: "EH", countryName: "Western Sahara" },
    { id: "ye", colorId: "16", countryCode: "YE", countryName: "Yemen" },
    { id: "zm", colorId: "17", countryCode: "ZM", countryName: "Zambia" },
    { id: "zw", colorId: "18", countryCode: "ZW", countryName: "Zimbabwe" },
    { id: "ax", colorId: "19", countryCode: "AX", countryName: "Åland Islands" }
  ]
];
