import { Color } from "$lib/shared/constants";
import type { HolidayCountry } from "$lib/shared/types";

export const countries: HolidayCountry[] = [
  { id: "us", countryCode: "US", countryName: "United States", color: Color[15] },
  { id: "in", countryCode: "IN", countryName: "India", color: Color[1] },
  { id: "cn", countryCode: "CN", countryName: "China", color: Color[2] },
  { id: "jp", countryCode: "JP", countryName: "Japan", color: Color[3] },
  { id: "de", countryCode: "DE", countryName: "Germany", color: Color[4] },
  { id: "gb", countryCode: "GB", countryName: "United Kingdom", color: Color[5] },
  { id: "kr", countryCode: "KR", countryName: "Korea, Republic of", color: Color[6] },
  { id: "br", countryCode: "BR", countryName: "Brazil", color: Color[7] },
  { id: "id", countryCode: "ID", countryName: "Indonesia", color: Color[8] },
  { id: "fr", countryCode: "FR", countryName: "France", color: Color[9] },
  { id: "ca", countryCode: "CA", countryName: "Canada", color: Color[10] },
  { id: "au", countryCode: "AU", countryName: "Australia", color: Color[11] },
  { id: "es", countryCode: "ES", countryName: "Spain", color: Color[12] },
  { id: "it", countryCode: "IT", countryName: "Italy", color: Color[13] },
  { id: "mx", countryCode: "MX", countryName: "Mexico", color: Color[14] },
  { id: "nl", countryCode: "NL", countryName: "Netherlands", color: Color[15] },
  { id: "sg", countryCode: "SG", countryName: "Singapore", color: Color[16] },
  { id: "se", countryCode: "SE", countryName: "Sweden", color: Color[17] },
  { id: "ch", countryCode: "CH", countryName: "Switzerland", color: Color[18] },
  { id: "ae", countryCode: "AE", countryName: "United Arab Emirates", color: Color[19] },
  { id: "pl", countryCode: "PL", countryName: "Poland", color: Color[20] },
  { id: "th", countryCode: "TH", countryName: "Thailand", color: Color[21] },
  { id: "sa", countryCode: "SA", countryName: "Saudi Arabia", color: Color[22] },
  { id: "tr", countryCode: "TR", countryName: "Turkey", color: Color[23] },
  { id: "ph", countryCode: "PH", countryName: "Philippines", color: Color[0] },
  { id: "vn", countryCode: "VN", countryName: "Vietnam", color: Color[1] },
  { id: "cz", countryCode: "CZ", countryName: "Czechia", color: Color[2] },
  { id: "cl", countryCode: "CL", countryName: "Chile", color: Color[3] },
  { id: "ar", countryCode: "AR", countryName: "Argentina", color: Color[4] },
  { id: "my", countryCode: "MY", countryName: "Malaysia", color: Color[5] },
  { id: "be", countryCode: "BE", countryName: "Belgium", color: Color[6] },
  { id: "at", countryCode: "AT", countryName: "Austria", color: Color[7] },
  { id: "no", countryCode: "NO", countryName: "Norway", color: Color[8] },
  { id: "dk", countryCode: "DK", countryName: "Denmark", color: Color[9] },
  { id: "mm", countryCode: "MM", countryName: "Myanmar (Burma)", color: Color[15] },
  { id: "ie", countryCode: "IE", countryName: "Ireland", color: Color[11] },
  { id: "fi", countryCode: "FI", countryName: "Finland", color: Color[12] },
  { id: "tw", countryCode: "TW", countryName: "Taiwan, Province of China", color: Color[13] },
  { id: "gr", countryCode: "GR", countryName: "Greece", color: Color[14] },
  { id: "pt", countryCode: "PT", countryName: "Portugal", color: Color[15] },
  { id: "ru", countryCode: "RU", countryName: "Russian Federation", color: Color[16] },
  { id: "za", countryCode: "ZA", countryName: "South Africa", color: Color[17] },
  { id: "eg", countryCode: "EG", countryName: "Egypt", color: Color[18] },
  { id: "pk", countryCode: "PK", countryName: "Pakistan", color: Color[19] },
  { id: "co", countryCode: "CO", countryName: "Colombia", color: Color[20] },
  { id: "pe", countryCode: "PE", countryName: "Peru", color: Color[21] },
  { id: "cr", countryCode: "CR", countryName: "Costa Rica", color: Color[22] },
  { id: "do", countryCode: "DO", countryName: "Dominican Republic", color: Color[23] },
  { id: "hu", countryCode: "HU", countryName: "Hungary", color: Color[0] },
  { id: "nz", countryCode: "NZ", countryName: "New Zealand", color: Color[1] },
  { id: "ua", countryCode: "UA", countryName: "Ukraine", color: Color[2] },
  { id: "az", countryCode: "AZ", countryName: "Azerbaijan", color: Color[3] },
  { id: "by", countryCode: "BY", countryName: "Belarus", color: Color[4] },
  { id: "bg", countryCode: "BG", countryName: "Bulgaria", color: Color[5] },
  { id: "hr", countryCode: "HR", countryName: "Croatia", color: Color[6] },
  { id: "ee", countryCode: "EE", countryName: "Estonia", color: Color[7] },
  { id: "ge", countryCode: "GE", countryName: "Georgia", color: Color[8] },
  { id: "lv", countryCode: "LV", countryName: "Latvia", color: Color[9] },
  { id: "lt", countryCode: "LT", countryName: "Lithuania", color: Color[10] },
  { id: "lu", countryCode: "LU", countryName: "Luxembourg", color: Color[11] },
  { id: "mt", countryCode: "MT", countryName: "Malta", color: Color[12] },
  { id: "om", countryCode: "OM", countryName: "Oman", color: Color[13] },
  { id: "qa", countryCode: "QA", countryName: "Qatar", color: Color[14] },
  { id: "ro", countryCode: "RO", countryName: "Romania", color: Color[15] },
  { id: "rs", countryCode: "RS", countryName: "Serbia", color: Color[16] },
  { id: "sk", countryCode: "SK", countryName: "Slovakia", color: Color[17] },
  { id: "si", countryCode: "SI", countryName: "Slovenia", color: Color[18] },
  { id: "uy", countryCode: "UY", countryName: "Uruguay", color: Color[19] },
  { id: "uz", countryCode: "UZ", countryName: "Uzbekistan", color: Color[20] },
  { id: "al", countryCode: "AL", countryName: "Albania", color: Color[22] },
  { id: "ad", countryCode: "AD", countryName: "Andorra", color: Color[23] },
  { id: "am", countryCode: "AM", countryName: "Armenia", color: Color[0] },
  { id: "bh", countryCode: "BH", countryName: "Bahrain", color: Color[1] },
  { id: "ba", countryCode: "BA", countryName: "Bosnia and Herzegovina", color: Color[2] },
  { id: "cy", countryCode: "CY", countryName: "Cyprus", color: Color[3] },
  { id: "is", countryCode: "IS", countryName: "Iceland", color: Color[4] },
  { id: "kw", countryCode: "KW", countryName: "Kuwait", color: Color[5] },
  { id: "md", countryCode: "MD", countryName: "Moldova, Republic of", color: Color[6] },
  { id: "me", countryCode: "ME", countryName: "Montenegro", color: Color[7] },
  { id: "aw", countryCode: "AW", countryName: "Aruba", color: Color[9] },
  { id: "bd", countryCode: "BD", countryName: "Bangladesh", color: Color[10] },
  { id: "bz", countryCode: "BZ", countryName: "Belize", color: Color[12] },
  { id: "bt", countryCode: "BT", countryName: "Bhutan", color: Color[13] },
  { id: "bo", countryCode: "BO", countryName: "Bolivia", color: Color[14] },
  {
    id: "bq",
    countryCode: "BQ",
    countryName: "Bonaire, Sint Eustatius and Saba",
    color: Color[15]
  },
  { id: "bf", countryCode: "BF", countryName: "Burkina Faso", color: Color[16] },
  { id: "kh", countryCode: "KH", countryName: "Cambodia", color: Color[17] },
  { id: "cm", countryCode: "CM", countryName: "Cameroon", color: Color[18] },
  { id: "cv", countryCode: "CV", countryName: "Cabo Verde", color: Color[19] },
  { id: "ky", countryCode: "KY", countryName: "Cayman Islands", color: Color[20] },
  { id: "ci", countryCode: "CI", countryName: "Côte d'Ivoire", color: Color[21] },
  { id: "cu", countryCode: "CU", countryName: "Cuba", color: Color[22] },
  { id: "cw", countryCode: "CW", countryName: "Curaçao", color: Color[23] },
  { id: "dj", countryCode: "DJ", countryName: "Djibouti", color: Color[0] },
  { id: "ec", countryCode: "EC", countryName: "Ecuador", color: Color[1] },
  { id: "gq", countryCode: "GQ", countryName: "Equatorial Guinea", color: Color[2] },
  { id: "er", countryCode: "ER", countryName: "Eritrea", color: Color[3] },
  { id: "et", countryCode: "ET", countryName: "Ethiopia", color: Color[4] },
  { id: "fo", countryCode: "FO", countryName: "Faroe Islands", color: Color[5] },
  { id: "gm", countryCode: "GM", countryName: "Gambia", color: Color[6] },
  { id: "gh", countryCode: "GH", countryName: "Ghana", color: Color[7] },
  { id: "gl", countryCode: "GL", countryName: "Greenland", color: Color[8] },
  { id: "gd", countryCode: "GD", countryName: "Grenada", color: Color[9] },
  { id: "gp", countryCode: "GP", countryName: "Guadeloupe", color: Color[10] },
  { id: "gu", countryCode: "GU", countryName: "Guam", color: Color[11] },
  { id: "gt", countryCode: "GT", countryName: "Guatemala", color: Color[12] },
  { id: "gg", countryCode: "GG", countryName: "Guernsey", color: Color[13] },
  { id: "gn", countryCode: "GN", countryName: "Guinea", color: Color[14] },
  { id: "gw", countryCode: "GW", countryName: "Guinea-Bissau", color: Color[15] },
  { id: "gy", countryCode: "GY", countryName: "Guyana", color: Color[16] },
  { id: "ht", countryCode: "HT", countryName: "Haiti", color: Color[17] },
  {
    id: "hm",
    countryCode: "HM",
    countryName: "Heard Island and McDonald Islands",
    color: Color[18]
  },
  { id: "va", countryCode: "VA", countryName: "Holy See", color: Color[19] },
  { id: "hn", countryCode: "HN", countryName: "Honduras", color: Color[20] },
  { id: "hk", countryCode: "HK", countryName: "Hong Kong", color: Color[21] },
  { id: "im", countryCode: "IM", countryName: "Isle of Man", color: Color[22] },
  { id: "jm", countryCode: "JM", countryName: "Jamaica", color: Color[23] },
  { id: "je", countryCode: "JE", countryName: "Jersey", color: Color[0] },
  { id: "jo", countryCode: "JO", countryName: "Jordan", color: Color[1] },
  { id: "ke", countryCode: "KE", countryName: "Kenya", color: Color[2] },
  { id: "ki", countryCode: "KI", countryName: "Kiribati", color: Color[3] },
  { id: "kg", countryCode: "KG", countryName: "Kyrgyzstan", color: Color[4] },
  { id: "la", countryCode: "LA", countryName: "Lao People's Democratic Republic", color: Color[5] },
  { id: "lb", countryCode: "LB", countryName: "Lebanon", color: Color[6] },
  { id: "ls", countryCode: "LS", countryName: "Lesotho", color: Color[7] },
  { id: "lr", countryCode: "LR", countryName: "Liberia", color: Color[8] },
  { id: "ly", countryCode: "LY", countryName: "Libya", color: Color[9] },
  { id: "mo", countryCode: "MO", countryName: "Macao", color: Color[10] },
  { id: "mg", countryCode: "MG", countryName: "Madagascar", color: Color[11] },
  { id: "mw", countryCode: "MW", countryName: "Malawi", color: Color[12] },
  { id: "mv", countryCode: "MV", countryName: "Maldives", color: Color[13] },
  { id: "ml", countryCode: "ML", countryName: "Mali", color: Color[14] },
  { id: "mh", countryCode: "MH", countryName: "Marshall Islands", color: Color[15] },
  { id: "mq", countryCode: "MQ", countryName: "Martinique", color: Color[16] },
  { id: "mr", countryCode: "MR", countryName: "Mauritania", color: Color[17] },
  { id: "mu", countryCode: "MU", countryName: "Mauritius", color: Color[18] },
  { id: "yt", countryCode: "YT", countryName: "Mayotte", color: Color[19] },
  { id: "fm", countryCode: "FM", countryName: "Micronesia, Federated States of", color: Color[20] },
  { id: "mn", countryCode: "MN", countryName: "Mongolia", color: Color[21] },
  { id: "ms", countryCode: "MS", countryName: "Montserrat", color: Color[22] },
  { id: "ma", countryCode: "MA", countryName: "Morocco", color: Color[23] },
  { id: "mz", countryCode: "MZ", countryName: "Mozambique", color: Color[0] },
  { id: "il", countryCode: "IL", countryName: "Israel", color: Color[1] },
  { id: "na", countryCode: "NA", countryName: "Namibia", color: Color[2] },
  { id: "nr", countryCode: "NR", countryName: "Nauru", color: Color[3] },
  { id: "np", countryCode: "NP", countryName: "Nepal", color: Color[4] },
  { id: "nc", countryCode: "NC", countryName: "New Caledonia", color: Color[5] },
  { id: "ni", countryCode: "NI", countryName: "Nicaragua", color: Color[6] },
  { id: "ne", countryCode: "NE", countryName: "Niger", color: Color[7] },
  { id: "nu", countryCode: "NU", countryName: "Niue", color: Color[8] },
  { id: "nf", countryCode: "NF", countryName: "Norfolk Island", color: Color[9] },
  { id: "mk", countryCode: "MK", countryName: "North Macedonia", color: Color[10] },
  { id: "mp", countryCode: "MP", countryName: "Northern Mariana Islands", color: Color[11] },
  { id: "pa", countryCode: "PA", countryName: "Panama", color: Color[12] },
  { id: "pg", countryCode: "PG", countryName: "Papua New Guinea", color: Color[13] },
  { id: "ps", countryCode: "PS", countryName: "Palestine, State of", color: Color[14] },
  { id: "py", countryCode: "PY", countryName: "Paraguay", color: Color[15] },
  { id: "pn", countryCode: "PN", countryName: "Pitcairn", color: Color[17] },
  { id: "pr", countryCode: "PR", countryName: "Puerto Rico", color: Color[18] },
  { id: "re", countryCode: "RE", countryName: "Réunion", color: Color[19] },
  { id: "rw", countryCode: "RW", countryName: "Rwanda", color: Color[20] },
  { id: "bl", countryCode: "BL", countryName: "Saint Barthélemy", color: Color[21] },
  {
    id: "sh",
    countryCode: "SH",
    countryName: "Saint Helena, Ascension and Tristan da Cunha",
    color: Color[22]
  },
  { id: "kn", countryCode: "KN", countryName: "Saint Kitts and Nevis", color: Color[23] },
  { id: "lc", countryCode: "LC", countryName: "Saint Lucia", color: Color[0] },
  { id: "mf", countryCode: "MF", countryName: "Saint Martin (French part)", color: Color[1] },
  { id: "pm", countryCode: "PM", countryName: "Saint Pierre and Miquelon", color: Color[2] },
  { id: "vc", countryCode: "VC", countryName: "Saint Vincent and the Grenadines", color: Color[3] },
  { id: "ws", countryCode: "WS", countryName: "Samoa", color: Color[4] },
  { id: "sm", countryCode: "SM", countryName: "San Marino", color: Color[5] },
  { id: "st", countryCode: "ST", countryName: "Sao Tome and Principe", color: Color[6] },
  { id: "sc", countryCode: "SC", countryName: "Seychelles", color: Color[7] },
  { id: "sl", countryCode: "SL", countryName: "Sierra Leone", color: Color[8] },
  { id: "so", countryCode: "SO", countryName: "Somalia", color: Color[9] },
  {
    id: "gs",
    countryCode: "GS",
    countryName: "South Georgia and the South Sandwich Islands",
    color: Color[10]
  },
  { id: "ss", countryCode: "SS", countryName: "South Sudan", color: Color[11] },
  { id: "lk", countryCode: "LK", countryName: "Sri Lanka", color: Color[12] },
  { id: "sd", countryCode: "SD", countryName: "Sudan", color: Color[13] },
  { id: "sr", countryCode: "SR", countryName: "Suriname", color: Color[14] },
  { id: "sj", countryCode: "SJ", countryName: "Svalbard and Jan Mayen", color: Color[15] },
  { id: "sy", countryCode: "SY", countryName: "Syrian Arab Republic", color: Color[16] },
  { id: "tj", countryCode: "TJ", countryName: "Tajikistan", color: Color[17] },
  { id: "tz", countryCode: "TZ", countryName: "Tanzania, United Republic of", color: Color[18] },
  { id: "tl", countryCode: "TL", countryName: "Timor-Leste", color: Color[19] },
  { id: "tg", countryCode: "TG", countryName: "Togo", color: Color[20] },
  { id: "tk", countryCode: "TK", countryName: "Tokelau", color: Color[21] },
  { id: "to", countryCode: "TO", countryName: "Tonga", color: Color[22] },
  { id: "tt", countryCode: "TT", countryName: "Trinidad and Tobago", color: Color[23] },
  { id: "tn", countryCode: "TN", countryName: "Tunisia", color: Color[0] },
  { id: "tm", countryCode: "TM", countryName: "Turkmenistan", color: Color[1] },
  { id: "tc", countryCode: "TC", countryName: "Turks and Caicos Islands", color: Color[2] },
  { id: "tv", countryCode: "TV", countryName: "Tuvalu", color: Color[3] },
  {
    id: "um",
    countryCode: "UM",
    countryName: "United States Minor Outlying Islands",
    color: Color[4]
  },
  {
    id: "ve",
    countryCode: "VE",
    countryName: "Venezuela, Bolivarian Republic of",
    color: Color[5]
  },
  { id: "vg", countryCode: "VG", countryName: "Virgin Islands, British", color: Color[6] },
  { id: "vi", countryCode: "VI", countryName: "Virgin Islands, U.S.", color: Color[7] },
  { id: "vu", countryCode: "VU", countryName: "Vanuatu", color: Color[8] },
  { id: "wf", countryCode: "WF", countryName: "Wallis and Futuna", color: Color[9] },
  { id: "eh", countryCode: "EH", countryName: "Western Sahara", color: Color[10] },
  { id: "ye", countryCode: "YE", countryName: "Yemen", color: Color[11] },
  { id: "zm", countryCode: "ZM", countryName: "Zambia", color: Color[12] },
  { id: "zw", countryCode: "ZW", countryName: "Zimbabwe", color: Color[13] },
  { id: "ax", countryCode: "AX", countryName: "Åland Islands", color: Color[14] }
];
